// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIhIdglr-bgLVBWldTgjs4Bf4Fg52QXZM',
    appId: '1:441124926151:web:7f979f6afd5a3b6bd484e2',
    messagingSenderId: '441124926151',
    projectId: 'alhomaidhi-34ab9',
    authDomain: 'alhomaidhi-34ab9.firebaseapp.com',
    storageBucket: 'alhomaidhi-34ab9.appspot.com',
    measurementId: 'G-WQ8VG4ZGHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcCZlAzInktsRBpLgwjfmYm6J2rfpFUg',
    appId: '1:441124926151:android:9cacc4758941d8f7d484e2',
    messagingSenderId: '441124926151',
    projectId: 'alhomaidhi-34ab9',
    storageBucket: 'alhomaidhi-34ab9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30rmuhe0G9MrM9W0ej0LLlxZfRELryUo',
    appId: '1:441124926151:ios:93e8969658fdb042d484e2',
    messagingSenderId: '441124926151',
    projectId: 'alhomaidhi-34ab9',
    storageBucket: 'alhomaidhi-34ab9.appspot.com',
    iosBundleId: 'com.example.alhomaidhiCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC30rmuhe0G9MrM9W0ej0LLlxZfRELryUo',
    appId: '1:441124926151:ios:e9ac2e70e40f92f4d484e2',
    messagingSenderId: '441124926151',
    projectId: 'alhomaidhi-34ab9',
    storageBucket: 'alhomaidhi-34ab9.appspot.com',
    iosBundleId: 'com.example.alhomaidhiCustomerApp.RunnerTests',
  );
}
